version: '3.8'

services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=restaurante_db
      - POSTGRES_USER=user_rest
      - POSTGRES_PASSWORD=pass_rest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Tu aplicación Backend (Spring Boot)
  backend:
    build: .
    container_name: spring_restaurante
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Mapeo exacto para tu application.properties
      - TZ=America/Costa_Rica
      - DB_HOST=db:5432
      - DB_RESTAURANTE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=prod